# Generated by Django 3.0.5 on 2020-05-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='user_name',
        ),
    ]
